apiVersion: v1
kind: Service
metadata:
  name: recette
  namespace: ingress-nginx
spec:
  ports:
  - port: 3306
  selector:
    app: recette

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
  
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  claimRef:
    name: mysql-pv-claim
    namespace: ingress-nginx
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: ingress-nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recette
  namespace: ingress-nginx
spec:
  selector:
    matchLabels:
      app: recette

  template:
    metadata:
      labels:
        app: recette
    spec:
      containers:
      - image: zafoutni/plannifrepas:feat-300
        name: recette
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: recettebis
          - name: MYSQL_ROOT_USER
            value: root
        ports:
        - containerPort: 3306
          name: recette
      #   volumeMounts:
      #   - name: mysql-persistent-storage
      #     mountPath: /var/lib/mysql
      # volumes:
      # - name: mysql-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: mysql-pv-claim

