version: '3.9'
services:
 mysqldb:
    build: .
    ports:
    - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD : root
    volumes: 
      - ./databasesrecette/dataSave:/var/lib/mysql
