version: '3.9'
services:
  db:
    build: .
    env_file:
      - ../randomPlanMeal/.env
    ports:
      - ${PORT}:${PORTC}
    # command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_ROOT_PASSWORD : root
    volumes: 
      - ./data:/var/lib/mysql
