version: '3.9'
services:
  db:
    build: .
    container_name: mysqlDemoStorage 
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD : root
    volumes: 
      - ./dataSave:/var/lib/mysql
