name: kubernete deploiement

on:
  push:
    branches: [ feat/microServicesApp ]

jobs:
  build-and-pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-pull
    steps:
    - uses: actions/checkout@main
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: "Configuration et connection a AKS"
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: product-aks1
        resource-group: product-resources
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/controller_ingress.yaml
          kubernetes/deployement_db.yaml
      
        
      
