name: kubernete deploiement

on:
  push:
    branches: [ feat/microServicesApp ]
##ff
jobs:
  build-and-pull:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello world!!!"
    - uses: actions/checkout@main
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    # - uses: azure/docker-login@v1
    #   with:
    #     login-server: docker.io
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # - run: docker build randomPlanMeal_SQLAlchemy/Dockerfile -t zafoutni/plannifrepas:feat-test
    # - run: docker push zafoutni/plannifrepas:feat-test
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-pull
    steps:
    - uses: actions/checkout@main
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: "Configuration et connection a AKS"
      uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: product-aks1
        resource-group: product-resources
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/deployement_db.yaml
          ./kubernetes/deployement_login.yaml
          ./kubernetes/deployement_random.yaml
          ./kubernetes/ingress.yaml
          ./kubernetes/secret.yaml
          ./kubernetes/service_login.yaml
          ./kubernetes/service_random.yaml
          ./kubernetes/service.yml
        # images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.repository.name }}:${{ github.ref_name }}
